name: mensajeria_servidor
description: Servidor de mensajería con JWT, bcrypt y SQLite
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.5.0
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.3.0
  sqlite3: ^2.4.2
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.12.2
  path: ^1.9.0
  uuid: ^3.0.7
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
